version: '3.1'

services:
  caddy:
    image: caddy:2.7-alpine
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy:/config
    command: caddy run --config /config/Caddyfile
    restart: unless-stopped
  server:
    build: ./iis-project/
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: ${MARIADB_USER}
      DB_PASS: ${MARIADB_PASS}
      DB_HOST: ${MARIADB_HOST}
      DB_PORT: ${MARIADB_PORT}
      DB_NAME: ${MARIADB_DB}
      GO_ENV: production
  db:
    image: mariadb:latest
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASS}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASS}
      MYSQL_DATABASE: ${MARIADB_DB}
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci